const plugin = require("tailwindcss/plugin");
const colors = require("tailwindcss/colors");
module.exports = {
  variants: {
    extend: {
      visibility: ["group-focus"],
    },
  },
  content: ["./src/**/*.{html,js}"],
  theme: {
    container: {
      padding: {
        DEFAULT: "1rem",
      },
    },
    extend: {
      colors: {
        primary: "#093D60",
        secondary: "#70BED2",
        light: "#FFFFFF",
        dark: "#062940",
        accent: "#FFCC00",
        grey: "#9FB2C0",
        lightgrey: "#F4F3F4",
        darkgrey: "#9FB2C0",
        success: "#00cc52",
        red: "#ef4444",
      },
      animation: {
        "infinite-scroll": "infinite-scroll 50s linear infinite",
        "infinite-scroll-reverse":
          "infinite-scroll-reverse 50s linear infinite",
      },
      keyframes: {
        "infinite-scroll": {
          from: { transform: "translateX(0)" },
          to: { transform: "translateX(-100%)" },
        },
        "infinite-scroll-reverse": {
          from: { transform: "translateX(-100%)" },
          to: { transform: "translateX(0%)" },
        },
      },
      boxShadow: {
        bal: "0px 10px 10px #0000004D",
      },
      spacing: {
        "1/2": "50%",
        "1/3": "33.333333%",
        "2/3": "66.666667%",
        "1/4": "25%",
        "2/4": "50%",
        "3/4": "75%",
        "1/5": "20%",
        "2/5": "40%",
        "3/5": "60%",
        "4/5": "80%",
        "1/6": "16.666667%",
        "2/6": "33.333333%",
        "3/6": "50%",
        "4/6": "66.666667%",
        "5/6": "83.333333%",
        "1/12": "8.333333%",
        "2/12": "16.666667%",
        "3/12": "25%",
        "4/12": "33.333333%",
        "5/12": "41.666667%",
        "6/12": "50%",
        "7/12": "58.333333%",
        "8/12": "66.666667%",
        "9/12": "75%",
        "10/12": "83.333333%",
        "11/12": "91.666667%",
      },
    },
    fontFamily: {
      sans: ["Raleway", "sans-serif"],
    },
  },
  safelist: [
    "is-info",
    "is-primary",
    "is-lightblue",
    "is-dark",
    "is-light",
    "is-outline",
    "is-external",
    "is-small-out",
    "is-white",
    "is-lightgrey",
    "is-darkgrey",
    "price",
    "checkmark",
    "checkmark-yellow",
    "checkmark-blue",
    "checkmark-lightblue",
    "checkmark-white",
    "dot",
    "dot-yellow",
    "dot-blue",
    "dot-lightblue",
    "opacity-10",
    "opacity-20",
    "opacity-30",
    "opacity-40",
    "opacity-50",
    "opacity-60",
    "opacity-70",
    "opacity-80",
    "opacity-90",
    "opacity-100",
    "md:basis-full",
    "md:basis-3/4",
    "md:basis-2/3",
    "md:basis-1/2",
    "md:basis-1/3",
    "md:basis-1/4",
    "lg:basis-full",
    "lg:basis-3/4",
    "lg:basis-2/3",
    "lg:basis-1/2",
    "lg:basis-1/3",
    "lg:basis-1/4",
    "border-1",
    "h-1",
    "h-2",
    "h-3",
    "h-4",
    "h-5",
    "w-2",
    "w-3",
    "w-4",
    "w-5",
    "w-7",
    "w-10",
    "w-1/2",
    "w-1/3",
    "w-1/4",
    "w-1/5",
    "w-1/6",
    "ml-100",
    "justify-center",
    "justify-start",
    "justify-end",
    "flex",
    "flex-row",
    "flex-col",
    "items-end",
    "flex-row-reverse",
    "flex-col-reverse",
    "text-left",
    "text-center",
    "text-right",
    "py-4",
    "lg:h-[50vh]",
    "lg:h-screen",
    "items-center",
    "min-h-20",
    "min-w-20",
    "mt-2",
    "mt-4",
    "mt-5",
    "mt-10",
    "mt-20",
    "mt-24",
    "mt-40",
    "mt-52",
    "mt-64",
    "mt-72",
    "mb-2",
    "mb-5",
    "mb-10",
    "mb-20",
    "mb-24",
    "mb-40",
    "mb-52",
    "mb-64",
    "mb-72",
    "pt-2",
    "pt-4",
    "pt-5",
    "pt-10",
    "pt-20",
    "pt-24",
    "pt-40",
    "pt-52",
    "pt-64",
    "pt-72",
    "pb-2",
    "pb-5",
    "pb-10",
    "pb-20",
    "pb-24",
    "pb-40",
    "pb-52",
    "pb-64",
    "pb-72",
    "min-h-[calc(50vh-39px)]",
    "lg:min-h-[calc(50vh-84px)]",
    "min-h-[calc(75vh-39px)]",
    "lg:min-h-[calc(75vh-84px)]",
    "min-h-[calc(100vh-78px)]",
    "lg:min-h-[calc(100vh-168px)]",
    "pb-1",
    "xl:pb-2",
    "pb-10",
    "xl:pb-24",
    "pb-24",
    "xl:pb-52",
    "pb-28",
    "xl:pb-64",
    "pb-32",
    "xl:pb-72",
    "pt-1",
    "xl:pt-2",
    "pt-10",
    "xl:pt-24",
    "pt-24",
    "xl:pt-52",
    "pt-28",
    "xl:pt-64",
    "pt-32",
    "xl:pt-72",
  ],
  plugins: [
    function ({ addComponents }) {
      addComponents({
        ".container-small": {
          maxWidth: "100%",
          padding: "0 2rem",
          "@screen sm": {
            maxWidth: "640px",
          },
          "@screen md": {
            maxWidth: "768px",
          },
          "@screen lg": {
            maxWidth: "920px",
          },
          "@screen xl": {
            maxWidth: "920px",
          },
          "@screen 2xl": {
            maxWidth: "1160px",
          },
        },

        ".container-tiny": {
          maxWidth: "100%",
          padding: "0 1rem",
          "@screen sm": {
            maxWidth: "480px",
          },
          "@screen md": {
            maxWidth: "640px",
          },
          "@screen lg": {
            maxWidth: "640px",
          },
          "@screen xl": {
            maxWidth: "720px",
          },
          "@screen 2xl": {
            maxWidth: "820px",
          },
        },
      });
    },
  ],
};
